version: 2

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: outline
    env:
      - CGO_ENABLED=1
    main: ./cmd/outline
    binary: outline
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - id: default
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE
      - CONTRIBUTING.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - 'merge conflict'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug fixes'
      regexp: '^.*?bug(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Performance improvements'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999

release:
  github:
    owner: sourceradar
    name: outline
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## Outline {{.Tag}}

    This release includes the command-line code analysis tool that generates structured outlines for multiple programming languages.

    ### Supported Languages
    - Go (.go files)
    - Java (.java files)
    - JavaScript (.js, .jsx files)
    - TypeScript (.ts, .tsx files)
    - Python (.py files)

  footer: |
    **Full Changelog**: https://github.com/sourceradar/outline/compare/{{ .PreviousTag }}...{{ .Tag }}

brews:
  - name: outline
    repository:
      owner: sourceradar
      name: homebrew-tap
    directory: Formula
    homepage: https://github.com/sourceradar/outline
    description: "Command-line code analysis tool that generates structured outlines for multiple programming languages"
    license: MIT
    dependencies:
      - name: go
        type: build
    test: |
      system "#{bin}/outline --help"

notarize:
  macos:
    - enabled: '{{ isEnvSet "MACOS_NOTARY_ISSUER_ID" }}'
      ids:
        - outline
      sign:
        certificate: "{{ .Env.MACOS_CERTIFICATE }}"
        password: "{{ .Env.MACOS_CERTIFICATE_PWD }}"
      notarize:
        issuer_id: "{{ .Env.MACOS_NOTARY_ISSUER_ID }}"
        key_id: "{{ .Env.MACOS_NOTARY_KEY_ID }}"
        key: "{{ .Env.MACOS_NOTARY_KEY }}"
        wait: true
        timeout: "20m"
