# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/rhysd/actionlint
    rev: v1.7.3
    hooks:
    -   id: actionlint
-   repo: local
    hooks:
    -   id: gofmt
        name: gofmt
        entry: gofmt -s -w
        language: system
        files: \.go$
