name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'
          cache: true

      - name: Run tests
        run: go test ./...

      - name: Run format check
        run: |
          go fmt ./...
          if [ -n "$(git status --porcelain)" ]; then
            echo "Code is not formatted. Run 'go fmt ./...' to fix."
            exit 1
          fi

      - name: Run vet
        run: go vet ./...

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'
          cache: true

      - name: Build Linux binaries
        run: |
          CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -o dist/outline-linux-amd64 ./cmd/outline
          CGO_ENABLED=1 GOOS=linux GOARCH=arm64 go build -o dist/outline-linux-arm64 ./cmd/outline

      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-binaries
          path: dist/outline-linux-*
          retention-days: 7

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'
          cache: true

      - name: Install Quill
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/quill/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Build macOS binaries
        run: |
          mkdir -p dist
          CGO_ENABLED=1 GOOS=darwin GOARCH=amd64 go build -o dist/outline-darwin-amd64 ./cmd/outline
          CGO_ENABLED=1 GOOS=darwin GOARCH=arm64 go build -o dist/outline-darwin-arm64 ./cmd/outline

      - name: Sign macOS binaries
        if: ${{ secrets.MACOS_CERTIFICATE != '' }}
        run: |
          echo "${{ secrets.MACOS_CERTIFICATE }}" | base64 --decode > cert.p12
          quill sign dist/outline-darwin-amd64
          quill sign dist/outline-darwin-arm64
          rm cert.p12
        env:
          QUILL_SIGN_P12: cert.p12
          QUILL_SIGN_PASSWORD: ${{ secrets.MACOS_CERTIFICATE_PWD }}

      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-binaries
          path: dist/outline-darwin-*
          retention-days: 7